WIP: add contributing.md file
OpenCodeFoundation/first-contributions pull request #12
Opened 2018-01-27 16:36 UTC by ratanparai

Work in progress. 

Will merge it after completing the guide

2018-01-28 03:19 UTC, mhmohona approved these changes
I think this is okay

2018-01-28 03:41 UTC, cseshohag approved these changes
Great;
Thank you @ratanparai Bhai for a good contribution guide line.

2018-01-28 06:22 UTC, mahedee requested changes

2018-01-28 06:22 UTC, mahedee commented on CONTRIBUTING.md
> +Before going deep into the steps please remember you **DO NOT NEED** to follow the remote name we used. You can use anything you want. You need to change your command depending on the name you choose
Please add overview of workflow diagram

2018-01-28 06:22 UTC, mahedee commented on CONTRIBUTING.md
> +- **upstream** - Remote name of `techcomdbd`'s repository.
What is upstream and origin. please explain before.

2018-01-28 06:22 UTC, mahedee commented on CONTRIBUTING.md
> +2. Clone the forked repository to your computer
Add like.. Clone the forked repository to your computer using the following command.

2018-01-28 06:22 UTC, mahedee commented on CONTRIBUTING.md
> +3. add upstream remote-
Explain why upstream remote

2018-01-28 06:22 UTC, mahedee commented on CONTRIBUTING.md
> +Check if the upstream remote added succesfully-
Use following command to check if the upstream remote added succesfully

2018-01-28 14:26 UTC, ratanparai commented on CONTRIBUTING.md
> +- **upstream** - Remote name of `techcomdbd`'s repository.
`origin` and `upstream` are English words. They do not have any special meaning in Git. I could choose any name. I do not have to use `upstream` and `origin` names as explained.

2018-01-28 14:35 UTC, ratanparai commented on CONTRIBUTING.md
> +2. Clone the forked repository to your computer
I have used commonly used language like [Configuring a remote fork](]https://help.github.com/articles/configuring-a-remote-for-a-fork/) or [git forks and upstream](https://www.atlassian.com/git/articles/git-forks-and-upstreams). Check there is no `run the following command` or anything like that. 

I think using those type of the same sentences may clutter the real contents.

2018-01-28 16:07 UTC, ratanparai commented
@mahedee can you review the changes?If there isn't any big problem with the guide then I think we should merge it and any small fixes can be applied in future PRs.

2018-01-29 06:09 UTC, mahedee approved these changes

2018-01-29 07:11 UTC, merged