Where to Contribute
OpenCodeFoundation/first-contributions pull request #14
Opened 2018-01-28 19:16 UTC by kamruldotnet

2018-01-28 19:17 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/techcombd/first-contributions?pullRequest=14) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/techcombd/first-contributions?pullRequest=14) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/techcombd/first-contributions?pullRequest=14) it.</sub>

2018-01-28 19:34 UTC, ratanparai approved these changes

2018-01-28 19:38 UTC, ratanparai requested changes

2018-01-28 19:38 UTC, ratanparai commented on Contributors.md
> +- [Kamrul hasan](https://github.com/kamruldotnet)
Isn't `H` of `hasan` should be capital later?

2018-01-28 19:38 UTC, aftabkajal approved these changes

2018-01-29 05:36 UTC, ratanparai approved these changes

2018-01-29 05:36 UTC, ratanparai approved these changes

2018-01-29 05:39 UTC, merged